name: movie_database
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_sign_in: ^5.4.0
  lottie: ^1.3.0
  flutter: 
    sdk: flutter
  cloud_firestore: ^3.2.1  
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.1.5
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  tmdb_api: ^2.1.3
dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true

  assets:
   
  - assets/lottie/23640-sign-in-or-sign-up-animation.json
  - assets/lottie/90397-log-in.json
  - assets/images/img_7.png
  - assets/lottie/81986-movie.json